  name: SMP
  main: me.mark.techsmp.Main
  version: 1.0
  api-version: 1.17
  commands:
    g:
      description: Interact with groups
      usage: /g <args>
    coords:
      description: Send cords
      usage: /coords
    setrole:
      description: Set a player's role
      usage: /setrole <player name> <rank name>
    bal:
      description: Get a player's balance
      usage: /bal
    pay:
      description: Pay a player
      usage: /pay <name> <amount>
    shop:
      description: Open the shop
      usage: /shop